### ISSUE TITLE
OpLog enabled makes PATCH return wrong _etag

### ISSUE THREAD

**Issue by msouder** [nicolaiarocci/eve#590]
It looks like the oplog_push function deletes the '_updated' entry from the document before the response _etag is made.  This means the _etag value in the database is different from what is returned in the response.

Here is the delete section from oplog_push from common.py (914-921):

           if op in ('PATCH', 'PUT', 'DELETE'):
                # these fields are already contained in 'entry'.
                del(update[config.LAST_UPDATED])
                # legacy documents (v0.4 or less) could be missing the etag
                # field
                if config.ETAG in update:
                    del(update[config.ETAG])
                entry['c'] = update

And here is the section from put_internal in put.py that shows we call resolve_document_etag then oplog_push then build_response_document. The oplog_push call modifies document, so the etag generated in the build_response_document doesn't match that generated in resolve_document_etag.

            resolve_document_etag(document)

            # skip 162-171 (writing to database)

            # update oplog if needed
            oplog_push(resource, document, 'PUT')

            insert_versioning_documents(resource, document)

            # notify callbacks
            getattr(app, "on_replaced")(resource, document, original)
            getattr(app, "on_replaced_%s" % resource)(document, original)

            # build the full response document
            build_response_document(
                document, resource, embedded_fields, document)

Is this the intended functionality?  You can call GET after the PATCH to get the correct etag, but a second PATCH call will fail.

**Comment by nicolaiarocci** [comment]
I'd say it's a bug :+1:

**Comment by nicolaiarocci** [comment]
You mean PUT, right?

**Comment by nicolaiarocci** [comment]
Should be fixed now. Thanks.

**Comment by msouder** [comment]
Sorry, I did mean PUT.  Just saw in oplog_push that it would also delete the config.LAST_UPDATED on PATCH and mixed the two together.  Regardless, it looks like the fix you implemented will solve everything.

**Comment by shtratos** [comment]
@nicolaiarocci this bug still happens when I add `POST` to `OPLOG_CHANGE_METHODS`

```
    OPLOG = True
    OPLOG_AUDIT = True  # log changes to the documents
    OPLOG_CHANGE_METHODS = ['POST', 'PATCH', 'PUT', 'DELETE']  # log POST requests in addition to default ones
```

Then I get `_updated == '1970-01-01T00:00:00Z'` in the `POST` response.

I think the problem is that `copy` used to make a copy of the document is a shallow copy and `document` is a list in case of `POST`: https://docs.python.org/3/library/copy.html#copy.copy
Verified this via debugger.

When I changed this line to use `deepcopy` instead, the bug disappeared:
https://github.com/pyeve/eve/blob/b04ee6e734cc5e5160bc485b1ba44e8da8eb4920/eve/methods/common.py#L1354

Could you please fix this?
